### ISSUE TITLE
calender with typescript

### ISSUE THREAD

**Issue by penkong** [Kiarash-Z/react-modern-calendar-datepicker#100]
I just copy paste basic usage of DatePicker from core concepts of https://kiarash-z.github.io/,
already in error and does not show why we have it .
app created with :
create-react-app appName --typescript

some body help.

**Comment by Kiarash-Z** [comment]
@thebrodmann Any idea? 🤔
![image](https://user-images.githubusercontent.com/20098648/71613481-02db6480-2bbc-11ea-959b-ba4595ffdddf.png)

**Comment by penkong** [comment]
![Capture-1](https://user-images.githubusercontent.com/46618662/71614027-69319a00-2b5e-11ea-8d22-f0393cb05ae8.PNG)

**Comment by thebrodmann** [comment]
It's important to define the `useState` generic type variable explicitly. Otherwise, it's returned value and callback function type will be just something like `null` and `(value: null) => null`.


```ts
function App() {
  const [day, setDay] = React.useState<Day>(null); // <- Explicitly defined type variable
  const [dayRange, setDayRange] = React.useState<DayRange>({ // <- Explicitly defined type variable
    from: null,
    to: null
  });
  const [days, setDays] = React.useState<Day[]>([]); // <- Explicitly defined type variable

  return (
    <>
      <DatePicker value={day} onChange={setDay} />
      <DatePicker value={dayRange} onChange={setDayRange} />
      <DatePicker value={days} onChange={setDays} />
    </>
  );
}
```

@penkong in the screenshot you provided, you are using a wrong `Day` type (properties are optional which is wrong IMO). Use the `Day` type from the package and it should work.

**Comment by thebrodmann** [comment]
We need to provide a section in documentation to explain the usage of the library with TypeScript.

**Comment by penkong** [comment]
> 
> 
> We need to provide a section in documentation to explain the usage of the library with TypeScript.

OF COURSE ,
 any way thanks team changed it to class base and it already works. 
thanks , 
I close it .

**Comment by penkong** [comment]
in this
`  const [day, setDay] = React.useState<Day>(null); `
you can not pass null , value of DatePicker don't accept it .

-------
ok we also have problem on class base style.
please give info for setDay() and type of event that it get.
` setDay = (e : type?????) => {
    this.setState({ day : what here???? })
}`

**Comment by penkong** [comment]
![Capture](https://user-images.githubusercontent.com/46618662/71617972-6c368580-2b72-11ea-95fb-651c8e86aad6.PNG)
![Capture2](https://user-images.githubusercontent.com/46618662/71617976-6f317600-2b72-11ea-9a66-7533215ea1c4.PNG)

**Comment by Kiarash-Z** [comment]
@penkong This is because you're using `locale="fa"`. Change it to `locale="en"` and it will work!

**Comment by Kiarash-Z** [comment]
@thebrodmann Can you please work on TypeScript documentation on website? (on branch `develop`)

**Comment by thebrodmann** [comment]
> please give info for setDay() and type of event that it get.

```ts
setDay: (value: Day) => void
setDayRange: (value: DayRange) => void
setDays: (value: Day[]) => void 
```

**Comment by thebrodmann** [comment]
@Kiarash-Z sure. I will work on it.

**Comment by vitorrubim1** [comment]
how do I get the useful month. I have a range of 30 days by default, and the calendar is always active last month, I want it to stay in the current month

ex:

//how are you doing

setDayRange ({
      from: {
        day,
        month,
        year,
      },
      to: {
        day: lastDay,
        month: lastMonth,
        year: lastYear,
      },
    });

<Calendar
        locale = {portugueseLocale}
       value = {dayRange}
        onChange = {setDayRange}
        maximumDate = {utils ('en'). getToday ()}
        shouldHighlightWeekends
        calendarClassName = "sociax-calendar"
      />

////


As I want

<Calendar
        locale = {portugueseLocale}
       value = {dayRange.to}
        onChange = {setDayRange}
        maximumDate = {utils ('en'). getToday ()}
        shouldHighlightWeekends
        calendarClassName = "sociax-calendar"
      />

but it doesn't work
