### ISSUE TITLE
When i click on DatePicker input (select a day), calendar doesn't show

### ISSUE THREAD

**Issue by mahdi-kargar** [Kiarash-Z/react-modern-calendar-datepicker#101]
since i used new version of (react-**modern**-calendar-datepicker), when i clicking on DatePicker input(select a day), calendar doesn't show. but previous version (react-**persian**-calendar-date-picker) works perfectly.
![image](https://user-images.githubusercontent.com/22619227/71618521-2363e880-2bd5-11ea-85af-8a2ee291b334.png)

i used project samples code (core-concepts).

`import React, { useState } from "react";
import DatePicker from "react-modern-calendar-datepicker";

const Pdp = () => {
  const [selectedDay, setSelectedDay] = useState(null);
  console.log(React.version);
  return (
    <DatePicker
      value={selectedDay}
      onChange={setSelectedDay}
      inputPlaceholder="Select a day"
      shouldHighlightWeekends
    />
  );
};

export default Pdp;`

thanks for your reply.

**Comment by Kiarash-Z** [comment]
Hi @mahdi-kargar, can you provide this on [CodeSandbox](https://codesandbox.io/) please?

**Comment by mahdi-kargar** [comment]
I'm sorry. i think, this is related to my project, and i couldn't be able to provide that on CodeSandbox (because of many dependencies required by the project). 
**in  a new react empty project, DatePicker works perfectly**. excuse me, but where can i play with z-index or any similarities in your awesome component to solve this problem. i think, it can be helpful.

i changed .DatePicker__calendarContainer{z-index}, .Calendar {z-index} and .DatePicker__calendarArrow{z-index} but nothing changed.

**Comment by Kiarash-Z** [comment]
@mahdi-kargar you can change zIndex of datepicker container by giving a class with `wrapperClassName` prop. BTW, if you can't resolve the issue, I can help you [in Telegram](https://telegram.me/Kiarash_Z).

**Comment by mahdi-kargar** [comment]
Thanks. There were **parallel css styles** (remained from old version), in projectFolder/**build/static/css** . i removed them, now it's working perfectly.
