### ISSUE TITLE
v2.1.0 roadmap

### ISSUE THREAD

**Issue by Kiarash-Z** [Kiarash-Z/react-modern-calendar-datepicker#105]
Here will be the new things in v2.1.0 🎉:
- Prop for locales strings + Week shift related to #99 
- Fix some bugs in month selection menu when it's open related to #97 
- Avoid common errors in default year value by showing a message related to #96 

Any idea is appreciated 🙏🏻

**Comment by thebrodmann** [comment]
Isn't it better to ship #96 and #97 through 2.0.1?

**Comment by Kiarash-Z** [comment]
@thebrodmann It's true that they're patch updates, but I'm planning to fix them along with introducing new features to the date picker; that's I want to bump to 2.1.0

**Comment by HosseinAlipour** [comment]
Is it backward compatible with v1? if not please provide the migration guide. thanks

**Comment by thebrodmann** [comment]
@HosseinAlipour now we are on version 2.0.0 which is not compatible with version 1.0.0 due to breaking change that has been explained in #90.

**Comment by thebrodmann** [comment]
> if not please provide the migration guide

Absolutely we need a guide for the breaking change. @Kiarash-Z  I think there was some issues related to it. So maybe it worth to add a migration guide from version 1.x.x to version 2.x.x to the documentation.

**Comment by Kiarash-Z** [comment]
@thebrodmann Anyway, no body's gonna read it 😑If people paid attention to breaking version change, and therefore, read the document, they wouldn't encounter such issues. I will add this section though...

**Comment by iksent** [comment]
@Kiarash-Z, hello!
When are you planning to release 2.1.0?

**Comment by Kiarash-Z** [comment]
@iksent Hi, hopefully, I will release this new version next week.

**Comment by Kiarash-Z** [comment]
@iksent new version is out 🎉you can use your own custom locale for the date picker. [You can do it like this](https://kiarash-z.github.io/react-modern-calendar-datepicker/docs/different-locales).
