### ISSUE TITLE
Use this calendar in web

### ISSUE THREAD

**Issue by mrmmg** [Kiarash-Z/react-modern-calendar-datepicker#109]
**Describe the solution you'd like**
Hi Kiarash... Is any option to use this calendar in web programming? I wanna use this in an HTML page like a date picker or calendar.
For example, I found a js library: [LINK](http://babakhani.github.io/PersianWebToolkit/doc/datepicker/example/)

**Comment by Kiarash-Z** [comment]
Hi Mehdi, this package is indeed for web though it's made for React. You can use it on any React project, but on vanilla JavaScript, it's not possible.
