### ISSUE TITLE
2.1.0 Bugs

### ISSUE THREAD

**Issue by iksent** [Kiarash-Z/react-modern-calendar-datepicker#110]
Hello, @Kiarash-Z!
Thanks a lot for your work, 2.1.0 do exactly what I need.

**But there are some bugs:**

1. `weekStartingIndex` do the work, calendar is now with the right shift. But our weekends are not correct. Don't it need to be shifted too?
I will disable `-weekend` styling for now (May be add prop for it's color like `colorPrimary`? :)

<img width="300px" src="https://user-images.githubusercontent.com/32956521/72314513-105f1700-36b1-11ea-983d-8b5c27285cd4.png"/>

2 If you pass `locale` prop and do not provide `getToday`, `toNativeDate` and other functions - calendar will crash.

![Example](https://user-images.githubusercontent.com/32956521/72314657-9a0ee480-36b1-11ea-81d5-95166f04e77a.png)

3. Please, add customizing `weekDays`-shortings. At Russia we have 2 letters in it, not just 1. But may be it will be good to provide custom array, just like `months` and `weekDays`.

**Comment by Kiarash-Z** [comment]
Hi @iksent, I'm glad this version meets your needs 😊

1- You can easily disable weekends' highlights by giving `shouldHighlightWeekends={false}` (removing it from passed props will do the trick as well)

2- Actually, it should crash 🤔 All the details for a custom language are mandatory. If the date picker can't get them properly, how is it supposed to work?

3- Sure, I'm sorry I didn't add a custom way to customize this. I will add this to the following version.

**Comment by iksent** [comment]
1 - Yeah, I have already remove this prop, but this is a workaround, because I just can't use this property, it highlights not correct weekends.

2 - Why all the details are mandatory? Why I just can't set up strings and do not change the common logic of picker? I think you need to use your functions, If user didn't provide his.

3 - Perfect, thanks.

**Comment by iksent** [comment]
Oh no! Why this does not work in IE, at least in 11 :((

It is possible to fix it?

<img src="https://user-images.githubusercontent.com/32956521/72509143-bdc85b00-3868-11ea-86ce-550855d8d726.png" width="200px"/>

**Comment by Kiarash-Z** [comment]
1- I will fix that! you will be able to determine your weekends in an array...
2- Because all formats for date values are stored in native locale not in common Gregorian locale.  I will do my best to reduce these details so you will only pass a function to convert Gregorian date to your native locale date.

**Comment by Kiarash-Z** [comment]
> Oh no! Why this does not work in IE, at least in 11 :((

Unfortunately, I'm not really planning to make this date picker work in IE. IE is an old browser, and it's missing support for many basic features.

**Comment by iksent** [comment]
Very sad, can't use it without IE11 :(

**Comment by Kiarash-Z** [comment]
@iksent IE is not important anymore. We're living in 2020. Unless you build your applications for dinosaurs, IE doesn't matter. Many huge companies like Apple don't support IE in for their website and they encourage you to use a newer browser...

**Comment by iksent** [comment]
I can’t influence this, people from the client's company use IE11.

**Comment by iksent** [comment]
Hello, @Kiarash-Z.
I figure out the problems at IE11 and suggest the easiest way:
Change your code a bit and write a guide on how to make compatibility with IE11.

**CHANGES**
1. IE not supports `classList.replace`
```
const handleSlideAnimationEnd = ({ target }) => {
  target.classList.remove('-hiddenNext');
  target.classList.remove('-hiddenPrevious');
  target.classList.remove('-shownAnimated');
  target.classList.add('-shown');
};
```

2. Wrapper CSS
```
.Calendar__sectionWrapper {
  position: relative;
  flex: 1;
  /* overflow: hidden; */ <---- Remove
}
```

```
.Calendar {
  ...
  overflow: hidden; <---- Add
  ...
}
```

3. Buttons CSS

Can't fix it by now, but I'll try it later again.

<img src="https://user-images.githubusercontent.com/32956521/72790803-0f515b00-3c58-11ea-8c87-0163dd84b1c6.png" width="200px"/>

4. DatePicker with input: Calendar will be closed when clicking at any place inside Calendar

Can't fix it by now, multiple onBlur events firing at IE11.

**GUIDE** (Inside developers' projects)

1. IE not supports CSS variables.
Can be fixed, for example, with [css-vars-ponyfill](https://jhildenbiddle.github.io/css-vars-ponyfill/#/)

Example with default values:
```
  useEffect(() => {
    cssVars({
      onlyLegacy: false,
      variables: {
        '--cl-color-primary': '#0eca2d',
        '--cl-color-primary-light': '#cff4d5',
        '--animation-duration': '0.4s',
        '--cl-color-black': '#444444',
        '--cl-color-disabled': '#d4d4d4',
        '--cl-color-error': '#ff2929',
      },
    });
  }, []);
```

2. Polyfills for IE

- Array.from
- Array.find
- Array.keys

```
<script crossorigin="anonymous" src="https://polyfill.io/v3/polyfill.min.js?features=Array.prototype.keys%2CArray.from%2CArray.prototype.find"></script>
```

3.

**Comment by Kiarash-Z** [comment]
Thank you @iksent ☺️, this is very nice. If I find a solution for the number 4, I would considering adding support for IE 11.

**Comment by Kiarash-Z** [comment]
@iksent in the latest version (3.0.1) you can specify your custom weekends and also specify the short month name 🎉 [Here's the documentation ](https://kiarash-z.github.io/react-modern-calendar-datepicker/docs/different-locales/)
