### ISSUE TITLE
Editable DatePicker

### ISSUE THREAD

**Issue by BabakYaghoobi** [Kiarash-Z/react-modern-calendar-datepicker#111]
Hi,
Thanks for great component,

How can use it like Material UI KeyboardDatePicker , both type manual or click button for open picker ?
like this : https://material-ui-pickers.dev/demo/datepicker

Regards

**Comment by Kiarash-Z** [comment]
Hi @BabakYaghoobi, I think using a keyboard for input to modify its value will lead to confusion for users. I'm not currently planning to implement such a feature.
