### ISSUE TITLE
Ui Problem

### ISSUE THREAD

**Issue by mahdibarati** [Kiarash-Z/react-modern-calendar-datepicker#112]
problem in ui:
![image](https://user-images.githubusercontent.com/33564973/72875930-95c67500-3d0a-11ea-90c0-2afb887b2790.png)

**Comment by thebrodmann** [comment]
Please load the CSS into your bundle as described in the [documentation](https://kiarash-z.github.io/react-modern-calendar-datepicker/docs/getting-started).
