### ISSUE TITLE
 initialValue of DatePicker in formik does not work

### ISSUE THREAD

**Issue by hamidrz021** [Kiarash-Z/react-modern-calendar-datepicker#114]
Hi
Thanks for your nice package
I read and implemented [this issue](https://github.com/Kiarash-Z/react-modern-calendar-datepicker/issues/76)
When i set the initial value of selected day everything is fine
But as soon as I click on Input of Datepicker I get an error :
"Invalid array length" and "The above error occurred in the DaysList component"
Then the app crashes
I also tried to remove the locale property but another error has been thrown
This occurrence is also available in your [CodeSandBox ](https://codesandbox.io/s/serene-fog-oob88-oob88?fontsize=14&hidenavigation=1&theme=dark)example

**Comment by thebrodmann** [comment]
The CodeSandBox you mentioned is a single day selector!

**Comment by hamidrz021** [comment]
I need this selector for birthDate
So i think this is ok and i want single day selector

**Comment by thebrodmann** [comment]
Are you flagging that the CodeSandBox you mentioned is not working and will crash when you click on input? I couldn't repro the issue. The mentioned CodeSandBox is working like a charm!

**Comment by hamidrz021** [comment]
This is my changes on [CodeSandBox](https://codesandbox.io/embed/react-modern-calendar-datepicker76-h3987?fontsize=14&hidenavigation=1&theme=dark) with locale = "fa" .

**Comment by thebrodmann** [comment]
There are two problems with CodeSandBox you mentioned.

1. typo

```jsx
<DatePicker
    value={field.value}
    onChange={value => formik.setFieldValue(name, value)}
    lacale="fa" // <- locale
/>
```
2. using `string` instead of `number` for properties of `Day` object (I'm not 100% sure about this. @Kiarash-Z, Am I right?)

BTW, after executing the above lines the last CodeSandBox you provided [will work](https://codesandbox.io/s/react-modern-calendar-datepicker76-03rbg?fontsize=14&hidenavigation=1&theme=dark).

**Comment by Kiarash-Z** [comment]
@thebrodmann Thanks for taking care of this issue 😊 

> using string instead of number for properties of Day object (I'm not 100% sure about this. @Kiarash-Z, Am I right?)

I think it wouldn't work.

**Comment by hamidrz021** [comment]
@Kiarash-Z It already works for my case
But as you can tell I'm not sure.
What's your solution?

**Comment by thebrodmann** [comment]
> I'm not sure.

About what?

**Comment by Kiarash-Z** [comment]
@hamidrz021 Use numbers!

**Comment by hamidrz021** [comment]
@thebrodmann  @Kiarash-Z  Thank you
