### ISSUE TITLE
 Calendar align issue

### ISSUE THREAD

**Issue by ahmadmrj** [Kiarash-Z/react-modern-calendar-datepicker#115]
**Time picker  is needed with date or separately**
I use your date picker and it's better than other Persian packages in some ways. 
But it doesn't have date picker.

I think, the ability of pick date and time in just one picker is good but if we could have this optional and can separate time and date picker it is a perfect one.

**Comment by Kiarash-Z** [comment]
Hi @ahmadmrj, sorry for the latency in response. Would publishing a separate time picker with lots of dedicated features resolve your issue? or it should be integrated to this date picker?

**Comment by ahmadmrj** [comment]
Thanks for your reply.

As I mentioned before, the ideal case would be having both options. but
currently I need separate timepicker element.

Regards.

**Comment by Kiarash-Z** [comment]
I would consider publishing a rich separate time picker with **some integrating options to this date picker**! BTW, you said that 

> it's better than other Persian packages in some ways.

Do you have any specific suggestions to improve this date picker?  It would be massively appreciated

**Comment by ahmadmrj** [comment]
Yes, I do. The date picker popup should  be able to open on top or bottom
of the input field depending on the page and form design. Your popup just
can be open on bottom. Having an option or being fluid according to space
around the input can improve your package.

**Comment by Kiarash-Z** [comment]
That's nice. I will consider it in the following version for sure.

**Comment by Kiarash-Z** [comment]
@ahmadmrj In the latest version(3.0.1), the date picker aligns perfectly from any side. Check it out! 🎉

**Comment by ahmadmrj** [comment]
Hey Kiarash,

Is it any config key to set align?

**Comment by Kiarash-Z** [comment]
@ahmadmrj Yes, you can change align manually by [`calendarPopperPosition ` prop.](https://kiarash-z.github.io/react-modern-calendar-datepicker/docs/props-list)
