### ISSUE TITLE
change display BUG

### ISSUE THREAD

**Issue by Mvahedii** [Kiarash-Z/react-modern-calendar-datepicker#116]
**Describe the bug**
i want to change default display in .DatePicker in /lib/DatePicker.css from 
`display:inline-block;`
to
`display:block;`

**Expected behavior**
the changes are not working

**Comment by Kiarash-Z** [comment]
I think you have the same issue as #117. Please let me know how you're applying your custom styles

**Comment by Kiarash-Z** [comment]
moved to #117
