### ISSUE TITLE
change text-align BUG

### ISSUE THREAD

**Issue by Mvahedii** [Kiarash-Z/react-modern-calendar-datepicker#117]
**Describe the bug**
i want to change default text-align in .DatePicker in /lib/.DatePicker__input.css from
`text-align: center;`
to
`text-align: right;`

**Expected behavior**
the changes are not working

**Comment by Kiarash-Z** [comment]
@Mvahedii Hi, how are you styling that? are you using a custom CSS class for input using `inputClassName` prop?

**Comment by Mvahedii** [comment]
Here is my Code : 

```
<DatePicker
                          value={this.selectDay}
                          inputClassName="birthday-date-picker"
                          locale="fa"
                        />
```
@Kiarash-Z

**Comment by Kiarash-Z** [comment]
@Mvahedii Can you reproduce the case in CodeSandBox please so I can investigate it better?

**Comment by Kiarash-Z** [comment]
Closed due to inactivity.
