### ISSUE TITLE
is there a way to add something to calendar/datepicker container?

### ISSUE THREAD

**Issue by namipsg** [Kiarash-Z/react-modern-calendar-datepicker#118]
hi , i want to put a button into container to change calendar locale using component's state between shamsi and gregorian , is there a way to implement it on react-modern-calendar-datepicker ?

**Comment by Kiarash-Z** [comment]
Hi @namipsg, inserting some HTML code in the calendar container is not possible yet. However, I might add a prop for rendering such stuff like a "select today" button in the next versions. Therefore, I'll keep this issue open for now...

**Comment by Kiarash-Z** [comment]
@namipsg in the new version (3.0.1) there's a new prop called `renderFooter`. You can use that to render such a button in the calendar now 🎉 Documents for this on [Customization page.](https://kiarash-z.github.io/react-modern-calendar-datepicker/docs/customization)

**Comment by namipsg** [comment]
Great 🎉 thanks ! damet Jizz

**Comment by spostad7** [comment]
hi @Kiarash-Z ,
I used renderFooter for display 'today' button, but it seems that it doesn't work as expected. I used the sample code for renderFooter but it changes nothing in the calendar

**Comment by Kiarash-Z** [comment]
@spostad7 Please make sure you're using the latest version of the package. If you're using the latest version and issue persists, please send me a reproduced version on [CodeSandBox](https://codesandbox.io/)

**Comment by spostad7** [comment]
@Kiarash-Z 
thanks for the fast reply. it was my mistake. the package didn't update from the last version
