### ISSUE TITLE
close/destroy after select today button

### ISSUE THREAD

**Issue by spostad7** [Kiarash-Z/react-modern-calendar-datepicker#123]
**Describe the bug**
In renderFooter, if the user clicks on today button the DatePicker does not close.

![localhost_3015_fa(iPad Pro)](https://user-images.githubusercontent.com/2351721/76706954-aab6f780-6700-11ea-93b9-a6c64ffddcea.png)

**Expected behavior**
The Datepicker is better to have onClose or destroy API/prop in which it invokes base on user action (click on a custom button or on calendar day)

**Comment by thebrodmann** [comment]
Maybe we can response to the input `value` change. Every time it has been changed the calender goes off.

**Comment by spostad7** [comment]
@thebrodmann
yes, it should be close on every value change. the today button changes the value to the current day but it doesn't close datepicker at all. Maybe an onClose or destroy callback is useful to close datepicker manually

**Comment by thebrodmann** [comment]
> Maybe an onClose or destroy callback is useful to close datepicker manually

For now, you can treat date picker like other inputs. Just change the focus of the page from the input of the date picker and then the date picker goes off.

**Comment by Kiarash-Z** [comment]
@spostad7 It's not a good practice to close the calendar for everything that is rendered in the footer, because not all the cases are today button. However, I'm thinking of exporting a custom `useDatePicker` hook and giving very useful utilities for such cases, it would be something like this:

```js
const { ref, close, open } = useDatePicker(); 

const selectToday = () => {
  // some stuff for selecting today
  close()
};

<DatePicker 
   ...
  ref={ref}
  renderFooter={() => <button onClick={selectToday}>today</button>}
/>
```

**Comment by Kiarash-Z** [comment]
For now, as @thebrodmann suggested an `input.blur()` will do it. But I think the above solution will be better If implemented in the next version.

**Comment by spostad7** [comment]
@Kiarash-Z 
thanks! That would be great and enough for my issue

**Comment by thebrodmann** [comment]
Is there any scenario in which the calendar should be closed without any change in the state?

**Comment by Kiarash-Z** [comment]
@spostad7 This custom `useDatePicker` hook would add a great deal of complexity and size to the package. Therefore, I decided to leave it for now. I would recommend using `input.blur()` to close the date picker after day selection. Sorry if it took long to discuss this 🙏🏻
