### ISSUE TITLE
abbr tag display [object object] as title

### ISSUE THREAD

**Issue by spostad7** [Kiarash-Z/react-modern-calendar-datepicker#124]

**Comment by Kiarash-Z** [comment]
Please describe your issue. This is so vague.

**Comment by spostad7** [comment]
@Kiarash-Z 
here is what happened when user hover on calendar WeekDays (e.g. ش/ی/د/س/چ/پ/ج):

![Annotation 2020-03-16 134535](https://user-images.githubusercontent.com/2351721/76746559-f2836080-678c-11ea-831a-3774762fa008.png)

**Comment by Kiarash-Z** [comment]
Oh, you're right. Thanks for the bug report. Will be fixed in the next version.

**Comment by Kiarash-Z** [comment]
Fixed on the latest release(3.0.3) 🎉
