### ISSUE TITLE
DateRange for DatePicker

### ISSUE THREAD

**Issue by spostad7** [Kiarash-Z/react-modern-calendar-datepicker#125]
I have two datepicker inputs and I want that user selects a date range. 

**this is the expected behavior:**
1- user clicks on the first datepicker input and selects the first day. now the start day must have class
 ```-selectedStart```
![start](https://user-images.githubusercontent.com/2351721/76785617-051c8a80-67cb-11ea-9956-f989ecb5e885.png)

2- user clicks on second datepicker input to select end day. this time datepicker have to keep the first value from first datepicker as 'from' and set new value as 'to'.
![end](https://user-images.githubusercontent.com/2351721/76787998-54fd5080-67cf-11ea-8fa7-ef28e6c399a4.png)

the question is how can I do this for two different datepicker (e.g. keeping selectedStart for second datepicker) and set selected value for each input?
a similar implementation is on  [alibaba hotel datepicker](https://www.alibaba.ir/hotel)

**Comment by thebrodmann** [comment]
Customize the input with `renderInput`.

**Comment by spostad7** [comment]
@thebrodmann 
It does not solve my issue at all because I have to show users two different dates that he chose. Also, one input datepicker has bad UX because the user has to click twice on that input to pick a date

**Comment by thebrodmann** [comment]
The example you provided is a single date picker with two inputs IMO!
![Screen Shot 2020-03-17 at 5 38 17 PM](https://user-images.githubusercontent.com/20781126/76867062-44ee7b00-687a-11ea-81a0-cdd5ec4bf53b.png)

**Comment by spostad7** [comment]
@thebrodmann 
In my case, I have two horizontal inputs that are stacked on each other. If the user clicks on one of them, it owns datepicker shows up and the user picks start or end day from them. So I can't have single datepicker with two inputs; firstly because of design and secondly for the sake of datepicker limitation!

![Annotation 2020-03-17 184015](https://user-images.githubusercontent.com/2351721/76870313-c6480c80-687e-11ea-8a62-f1de89e6d5c9.png)

**Comment by thebrodmann** [comment]
So... 🤔

If you want to use a range date picker, the first date picker should be single day selection.
By the first date picker (single day selection) user will select the `from` property of the second date picker.

> Also, it is good to mention that the input value for dateRange should have 'from' and 'to' value together. 

I think it's not obligated to have both values simultaneously.

```ts
{ from: { day: 11, month: 3, year: 2020 }, to: null }
{ from: null, to: { day: 11, month: 3, year: 2020 } }
```

**Comment by spostad7** [comment]
> If you want to use a range date picker, the first date picker should be single day selection.
By the first date picker (single day selection) user will select the from property of the second date picker

good suggestion! now the question is how can I show second input value? as I checked the document there is no way to show the selected range in datepicker as input value because the value of DatePicker should be an object of 'from' and 'to' value and it is not possible to show only 'to' value in the input

**Comment by thebrodmann** [comment]
> it is not possible to show only 'to' value in the input

It's possible. I showed you the initial state in my last comment!

**Comment by spostad7** [comment]
thanks, @thebrodmann!
this is final try on selecting a range from datepicker. at last, I format the input date and show the user only the 'to' value. for 'from' datepicker I used single date selection and for 'to' datepicker I used date range including an object that has 'from' and 'to' value.

```
export class SearchHotel extends PureComponent {
	constructor(props) {
		super(props);
		this.state = {
			dateRange: {
				from: null,
				to: null
			},
			fromDate: null,
			toDate: null
		};
	}

	

	onFromDateChange = date => {
		this.setState(prevState => ({
			fromDate: date,
			dateRange: {
				...prevState.dateRange,
				from: date
			}
		}));
	};

	onToDateChange = date => {
		if (!this.state.fromDate) {
			alertify
				.delay(4000)
				.closeLogOnClick(true)
				.error('لطفا ابتدا تاریخ ورود را انتخاب کنید');
			return false;
		}
		this.setState({
			fromDate: date.from,
			dateRange: date
		});
	};

	formatDateInput = () => {
		if (!this.state.dateRange.to) return '';
		const toDate = this.state.dateRange.to
		const year = toDate.year.toString();
		const month = toDate.month.toString().padStart(2, 0);
		const day = toDate.day.toString().padStart(2, 0);
		return `${year}/${month}/${day}`;
	};

	render() {
		const props = this.props;
		return (
			<form className={this.props.className} onSubmit={this.handleSearch}>
				
				<div
					className={this.props.className + '__fieldset mb-20 mt-20'}>
					<Label className={this.props.className + '__label'}>
						تاریخ ورود
					</Label>
					<DatePicker
						className={props.className}
						minimumDate={utils('fa').getToday()}
						value={this.state.fromDate}
						onChange={this.onFromDateChange}
						renderFooter={() => (
							<div
								style={{
									display: 'flex',
									justifyContent: 'center',
									alignItems: 'center'
								}}>
								<button
									type="button"
									onClick={() =>
										console.log(
											'today',
											this.state.persianToday
										)
									}
									className="btn DatePicker__footer-btn">
									امروز
								</button>
							</div>
						)}
					/>
				</div>
				<div className={this.props.className + '__fieldset mb-20'}>
					<Label className={this.props.className + '__label'}>
						تاریخ خروج
					</Label>
					<DatePicker
						className={props.className}
						minimumDate={utils('fa').getToday()}
						value={this.state.dateRange}
						onChange={this.onToDateChange}
						formatInputText={this.formatDateInput}
						renderFooter={() => (
							<div
								style={{
									display: 'flex',
									justifyContent: 'center',
									alignItems: 'center'
								}}>
								<button
									type="button"
									onClick={() =>
										console.log(
											'today',
											this.state.persianToday
										)
									}
									className="btn DatePicker__footer-btn">
									امروز
								</button>
							</div>
						)}
					/>
				</div>
			</form>
		);
	}
}
```

**Comment by thebrodmann** [comment]
So looks like this issue can be closed.

**Comment by Kiarash-Z** [comment]
@thebrodmann thank you for taking care of this issue, highly appreciate that 😊
