### ISSUE TITLE
Wrong position when multiple picker come near together.

### ISSUE THREAD

**Issue by mammad2c** [Kiarash-Z/react-modern-calendar-datepicker#126]
**Describe the bug**
When multiple datepicker input come near together, the input show over the Datepicker.

![image](https://user-images.githubusercontent.com/16647736/76890686-0a4a0a00-689d-11ea-81ea-4e3337f68740.png)

to see problem, go in [Customization Page](https://kiarash-z.github.io/react-modern-calendar-datepicker/docs/customization) 
- inspect element
- remove div that holds the code highlights to make two inputs near together
- now click on top input, you can see the bottom input take over the Datepicker

**Reproduced Version on CodeSandbox**
No need

**Expected behavior**
Datepicker should be on top of next input,  

** Solution **
if add a open class to Datepicker with higher z-index you can fix it.

**Comment by Kiarash-Z** [comment]
Thanks for the bug report, I will fix this soon.

**Comment by Kiarash-Z** [comment]
That was an issue with some extra classes I added to the customized input in the website documents. Fixed now 😊
