### ISSUE TITLE
Locale prop is expecting a string, not an object

### ISSUE THREAD

**Issue by simonpal** [Kiarash-Z/react-modern-calendar-datepicker#130]
**Describe the bug**
I'm trying to change the locale settings to fit my need according to this documentation: https://kiarash-z.github.io/react-modern-calendar-datepicker/docs/different-locales

**Expected behavior**
Be able to set the customLocale object to the locale prop, but locale is expecting a string instead of interface Locale

**Comment by Kiarash-Z** [comment]
@simonpal Sorry about that. I fixed it on the latest version. Can you please install the latest version (3.0.3) and check this again?

**Comment by Kiarash-Z** [comment]
Closed due to inactivity. This is fixed in the latest version by the way 🎉
