### ISSUE TITLE
Add purge css ignore comment

### ISSUE THREAD

**Issue by masihjahangiri** [Kiarash-Z/react-modern-calendar-datepicker#133]
**Describe the bug**
Purge css plugin remove date picker css.

Please add purge css ignore comment to first and last line of `react-modern-calendar-datepicker/lib/DatePicker.css` to solve this bug.
```
/* purgecss start ignore */
{ DatePicker CCSs }
/* purgecss end ignore */
```

**Comment by Kiarash-Z** [comment]
Hi, this doesn't make sense. Where do you import the CSS file of the library? if you're importing it in the same file that you're using the date picker, Purge should detect it as a used style and therefore, it wouldn't remove styles.

**Comment by masihjahangiri** [comment]
I solve my issue with change post-css config. I add `./node_modules/react-modern-calendar-datepicker/**/*.js` to `content` config array :
```javascript
const tailwindcss = require('tailwindcss');
const autoprefixer = require('autoprefixer');
const purgeCss = require('@fullhuman/postcss-purgecss');
const cssNano = require('cssnano');

const isProduction = process.env.NODE_ENV === 'production';
const purgeCssConfig = purgeCss({
  // Specify the paths to all of the template files in your project
  content: [
    './src/index.html',
    './src/**/*.jsx',
    './src/**/*.tsx',
    './node_modules/react-modern-calendar-datepicker/**/*.js',
  ],
  // Include any special characters you're using in this regular expression
  defaultExtractor: content => content.match(/[\w-/:]+(?<!:)/g) || [],
});

module.exports = {
  plugins: [
    // postCssImport,
    tailwindcss('./tailwind.config.js'),
    ...(isProduction ? [purgeCssConfig, cssNano({ preset: 'default' })] : []),
    autoprefixer,
  ],
};
```
But I still have problem.
![Untitled](https://user-images.githubusercontent.com/35561271/78133803-5d42c600-7434-11ea-9015-bd6308780610.png)
Above `defaultExtractor` config have issue with date picker css classNames.
All className don't pass through the `defaultExtractor` filter. I think that must change my `defaultExtractor` filter config.

**Comment by Kiarash-Z** [comment]
@masihjahangiri Can you please reproduce this on CodeSandBox or if it's not possible to config purge there, provide a repo for me to investigate the case more carefully?

**Comment by Kiarash-Z** [comment]
Closed due to inactivity
