### ISSUE TITLE
custom Font

### ISSUE THREAD

**Issue by mohammadsadeghforoughi** [Kiarash-Z/react-modern-calendar-datepicker#134]
hi, this is awesome Persian handled datepicker; but I can't modify the default font family. 
where and how I can change the font family. 
I use ```<Datepicker>``` + input; I want to change entire datepicker font (Days numbers)

**Comment by richardbruskowski** [comment]
Not a maintainer or contributor, but the `font-family` is inherited, so I think you should be able to change it by defining the `font-family` of a parent element (or even globally):

```jsx
<div style={{fontFamily: YourFontFamily}}><DatePicker /></div>
```

**Comment by Kiarash-Z** [comment]
@richardbruskowski is absolutely right. As I mentioned in [Getting Started ](https://kiarash-z.github.io/react-modern-calendar-datepicker/docs/getting-started) page, `font-family` is inherited.

**Comment by mohammadsadeghforoughi** [comment]
thank you
I changed the font-family but in this part, no font changed;
[here](https://imgur.com/bBoKDWJ)
@Kiarash-Z  @richardbruskowski

**Comment by Kiarash-Z** [comment]
@mohammadsadeghforoughi I think there's a problem in addressing your font. Can you reproduce this on [CodeSandBox](https://codesandbox.io/) please?

**Comment by mohammadsadeghforoughi** [comment]
I used ```Yekan``` font entire of my app, but in this section is not applied.
the strange thing is I can't select days in ```inspect element``` because of the datepicker hides if I can see CSS properties I can debug it.
i think i have some problem in my code but the closing datepicker in selecting ```inspect element``` is an issue. @Kiarash-Z

**Comment by Kiarash-Z** [comment]
@mohammadsadeghforoughi Temporarly, you can use `Calendar` component instead of `DatePicker` component to inspect elements easily.

**Comment by mohammadsadeghforoughi** [comment]
thank you so much, I'll test it tomorrow.
@Kiarash-Z

**Comment by Kiarash-Z** [comment]
@mohammadsadeghforoughi Did you get it working?

**Comment by mohammadsadeghforoughi** [comment]
Yes, I used the ```<Calendar>``` and I see the font-family inherited as you said, but still font not applied, I catch the bug; in the component, Persian Numbers is Persian, not English (in Standard keyboard, top numbers) and my font family have not numerical fonts for Persian numbers. 
I have to change the font family
Thank you so much for your time to help me.
@Kiarash-Z

**Comment by Kiarash-Z** [comment]
It's recommended to use Iran Sans o Iran Yekan fonts. I'm assuming this issue has been resolved. I close this.
