### ISSUE TITLE
DropDown doesn't work as expected

### ISSUE THREAD

**Issue by sinamoradi1375** [Kiarash-Z/react-modern-calendar-datepicker#138]
The thing is,  no matter wherever I put the Datepicker, It always pops up to the top side of the input and it doesn't care about the location of scroll which it should open to the bottom side.
I'm using react semantic ui and I'm not sure if it's the reason for this conflict

![Screenshot (7)](https://user-images.githubusercontent.com/38537095/78134443-68e2bc80-7435-11ea-8ffe-bf9dd1af5818.png)

**Comment by Kiarash-Z** [comment]
In the screenshot you've provided, it shouldn't open from bottom because there's not enough space over there(your dev tools got some space). If you provide an example on CodeSandBox, I can investigate it easily.

**Comment by sinamoradi1375** [comment]
Thank you for your response in such a short notice, I'll keep you posted
