### ISSUE TITLE
Include another default language

### ISSUE THREAD

**Issue by devbarreto** [Kiarash-Z/react-modern-calendar-datepicker#139]
**Is your feature request related to a problem? Please describe.**
This is a nice component in Brazilians vision. Although is not a problem in fact everytime that we want to use this calendar, we may send that whole langage locale param  (that have some problems with compatibility in last version @3.0.5)

**Describe the solution you'd like**
So I would like to include one more locale option: "pt-BR". Where will have something like this:
```
ptBR: {
    months: GREGORIAN_MONTHS_BR,
    weekDays: GREGORIAN_WEEK_DAYS_BR,
    weekStartingIndex: 0,
    getToday(gregorainTodayObject) {
      return gregorainTodayObject;
    },
    toNativeDate(date) {
      return new Date(date.year, date.month - 1, date.day);
    },
    getMonthLength(date) {
      return new Date(date.year, date.month, 0).getDate();
    },
    transformDigit(digit) {
      return digit;
    },
    nextMonth: 'Mês seguinte',
    previousMonth: 'Mês anterior',
    openMonthSelector: 'Escolher o mês',
    openYearSelector: 'Escolher o ano',
    closeMonthSelector: 'Fechar seleção mensal',
    closeYearSelector: 'Fechar seleção anual',
    from: 'de',
    to: 'até',
    defaultPlaceholder: 'Selecione...',
    digitSeparator: ',',
    yearLetterSkip: 0,
    isRtl: false,
  },
};
```

**Describe alternatives you've considered**
In terms of code I think that create one gregorian months and weeks builder for all possible languages.
In a general vision we could include [moment](https://www.npmjs.com/package/moment) as dependency, that it's one consolidated library who can allow us to work with many other languages.

**Comment by Kiarash-Z** [comment]
> in fact everytime that we want to use this calendar, we may send that whole langage locale param

You don't need to do that. You can create a common component called `MyDatePicker.js` in which you pass the language once and use it everywhere!

> that have some problems with compatibility in last version @3.0.5

Can you explain the compatibility issue please?

**Comment by devbarreto** [comment]
> You don't need to do that. You can create a common component called `MyDatePicker.js` in which you pass the language once and use it everywhere!

Later I resolve to try on this way. Happily my application worked how we expect with the unification of the configuration.

I'm sorry for the inconvenience. You can close this PR.

Thanks for your attention.
