### ISSUE TITLE
Close Date Picker When Selected Year Or Month in Firefox

### ISSUE THREAD

**Issue by Ramezanbeik** [Kiarash-Z/react-modern-calendar-datepicker#140]
Hello
First of all, I have to thank your excellent component.
Question:
Due to a special situation, I have to use Firefox browser version 47.0.1.
But] why, just after the month or year is selected from the list, the  DatePicker closed and is no longer displayed on the day selection page.
If possible, guide me in this regard.
Thank you very much

**Comment by Kiarash-Z** [comment]
@Ramezanbeik Can you please record the situation and share the video here so I can investigate it?

**Comment by Kiarash-Z** [comment]
Closed due to inactivity
