### ISSUE TITLE
popperPlacement prop

### ISSUE THREAD

**Issue by SidMorad** [Kiarash-Z/react-modern-calendar-datepicker#141]
**Is your feature request related to a problem? Please describe.**
I am using `DatePicker` inside this component which doesn't show `DataPicker`'s popper when opens at the top. So I would like to force `DatePicker` to open it's popper at bottom.

**Describe the solution you'd like**
I found [this comment](https://github.com/Hacker0x01/react-datepicker/issues/1246#issuecomment-361833919) helpful.

**Describe alternatives you've considered**
I was thinking about using `Calendar` inside a `Modal` as alternative, which need more code to write.

**Comment by Kiarash-Z** [comment]
@SidMorad This is a nice feature. Thanks for suggesting it. I will add this property to the next version. Till then, I keep this issue open

**Comment by Kiarash-Z** [comment]
@SidMorad This prop is now implemented 🎉You can use `calendarPopperPosition` in the latest version(3.1.0). It can take one of these values, `'auto'`(default), `'top'`, and `'bottom'`. For your case, you can simply pass `'bottom'` as a value to it 😊
