### ISSUE TITLE
Adding name property

### ISSUE THREAD

**Issue by s-mahdi** [Kiarash-Z/react-modern-calendar-datepicker#142]
Hello pals.
I'm using the **react-hook-form** for my forms and also `<DatePicker />` as an input.

There is no problem with submitting. but for passing the value of `input`, I have to set up a state and pass it **or** use `setValue` of **react-hook-form** which both are kind of pain! if there is a `name` property for `input` of `<DatePicker />` there is no more need to struggle with `states` and `setValue` and blah blah blah...
and I know there are a ton of ways to set the `name` property like using `renderInput` prop but I think a single prop will `setLife("easier")`.
thanks in advance.

**Comment by Kiarash-Z** [comment]
Hi, this is the coolest issue language I've ever seen. I will add this prop in the next version 😊

**Comment by Kiarash-Z** [comment]
@s-mahdi There you go. The new `inputName` prop is available in this new version(3.1.0). Install the latest version and enjoy 😊
