### ISSUE TITLE
Ranged Date Picker Doesn't Work With undefined Values in TypeScript

### ISSUE THREAD

**Issue by thebrodmann** [Kiarash-Z/react-modern-calendar-datepicker#147]
**Describe the bug**
As revealed by #146. Ranged date picker brakes in runtime during selection of from date when the value is `{ from: undefined, to: undefined }`. 

**Reproduced Version on CodeSandbox**
Here it is on [CodeSandBox](https://codesandbox.io/s/react-modern-calendar-datepicker146-m5srq?file=/src/index.js)

**Expected behavior**
It should work like a charm as always did. 💪🏻

**Comment by Kiarash-Z** [comment]
Thanks for the bug report. This will be fixed in the next minor release.

**Comment by Kiarash-Z** [comment]
Oh, @thebrodmann. I noticed the version in CodeSandBox is 1.1.0 😂. It actually works with newer versions. I remembered fixing this issue 😁

**Comment by Kiarash-Z** [comment]
I must say this is just an issue in TypeScript

**Comment by Kiarash-Z** [comment]
undefined value for JavaScript was working fine. Added the support for TypeScript in 3.1.3😊

**Comment by thebrodmann** [comment]
> I noticed the version in CodeSandBox is 1.1.0 😂

OMG! sorry for wasting your time on this! I forked it from an old sandbox!
