### ISSUE TITLE
[DayRangePicker] onChange function call is not calld directly after selected dates

### ISSUE THREAD

**Issue by hieu-t-code** [Kiarash-Z/react-modern-calendar-datepicker#150]
Hey guys,

so I have the following issue. I included a day range picker to my project. I want to do some stuff with all selected day between the selected day range. The thing is that the array is not filled with the days, unless I selected a day range and then reselecting one day. 

1. Selecting a day range => array with selected days is still empty
2. Reseleicting one day => the array is filled with the previous selected day range.

here is my code:

```
//this function pushes the dates in the date array
function getChartCategories(startDate: Date, endDate: Date): Array<string> {
    const dates: Array<string> = [];
    const currentDate = new Date(startDate);
    let currentMonth: number;
    while (currentDate <= endDate) {
        currentMonth = calculateCurrentMonth(currentDate.getMonth());
        dates.push(formatDateToIso8601(currentDate, currentMonth));
        currentDate.setHours(0);
        currentDate.setDate(currentDate.getDate() + 1);
    }
    return dates;
}

function createStartDate(dayRange: DayRange): Date {
    return new Date(
        dayRange?.from?.year?.toString() +
            '-' +
            dayRange?.from?.month?.toString() +
            '-' +
            dayRange?.from?.day?.toString(),
    );
}

function createEndDate(dayRange: DayRange): Date {
    return new Date(
        dayRange?.to?.year?.toString() + '-' + dayRange?.to?.month?.toString() + '-' + dayRange?.to?.day?.toString(),
    );
}


const selectedDates = getChartCategories(createStartDate(selectedDayRange), createEndDate(selectedDayRange));
foo(){
console.Log('123') // is executed after each selection
//do some stuff with the selected days (all days are in an string array)
}
onChange = {v =>
foo();
setSelectedDayRange(v);}

```

**Comment by Kiarash-Z** [comment]
Hi @hieu-t-code. This should actually work. Can you reproduce this on [CodeSandBox](https://codesandbox.io/) please?

**Comment by thebrodmann** [comment]
So, I think this is not related to the library.
You need another state to track the history of the changes. Just bring another `useState` hook which accumulate changes.

As a simple example:
```ts
function c() {
  const [dayRange, setDayRange] = useState({ from: undefined, to: undefined })
  const [history, setHistory]   = useState([])
  
  function handleChange(value) {
    setHistory([...history, value])
    setDayRange(value)
  }

  return <Calendar value={dayRange} onChange={handleChange} /> 
}
```

**Comment by hieu-t-code** [comment]
Yeah its not an issue related to the library. Thanks for the suggestion :D

**Comment by Kiarash-Z** [comment]
@hieu-t-code Has your issue been resolved? If not, just feel free to reproduce it on CodeSandBox, and we will do our best to help you. Even if it's not related to the library 😊

**Comment by hieu-t-code** [comment]
I'm gonna work tomoorow on this issue again. Thank you guys for you support.

**Comment by hieu-t-code** [comment]
@Kiarash-Z, I tried it now for several hours. I recreated the case, I'm not able to find a solution....

Steps to recreate the problem:
1. Selecting a day range e.g. lets say 27.04.2020 - 30.04.2020 console logs two empty arrays, 

2. after reselecting one day the console.logs: [2020-04-27, ... , 2020-04-30].

I need to fill the array after I picked the second date. Thanks in advance for you help!

https://codesandbox.io/s/confident-robinson-7pgq0?file=/src/App.tsx

**Comment by Kiarash-Z** [comment]
@hieu-t-code There's a problem with this approach. Currently, you try to access `selectedDates` in `handleDaySelection`(handler for `onChange`), but the thing is setting state in react is async. Therefore immediately after updating the state in `handleDaySelection`, you can't access the latest updated value! There are three solutions for this which I presented in my [forked CodeSandBox.](https://codesandbox.io/s/sharp-payne-zlr8b?file=/src/App.tsx:0-4009):
```js
function handleDaySelection(days: DayRange) {
  setSelectedDayRange(days);
  // solution 1 ✅: move selectedDates to here and pass days: 
  // const selectedDates = getDays(createStartDate(days.from), createEndDate(days.to));
}
console.log(selectedDates); // solution 2 ✅: log it outside of onChange handler

// solution 3 ✅: useEffect!
// React.useEffect(() => {
//   if (selectedDayRange.from && selectedDayRange.to) {
//     // do stuff
//   }
// }, [selectedDayRange])
```

**Comment by hieu-t-code** [comment]
I had in mind that it could be async, and couldn't use the first solution as the const is needed somewhere else in my code! 

The other two solutions are exactly what I needed. Thanks a lot for your time!

**Comment by Kiarash-Z** [comment]
@hieu-t-code You're welcome. I'm so happy that your issue has been resolved 😊
