### ISSUE TITLE
How do I get the calendar to pop up over a material-ui menu bar?

### ISSUE THREAD

**Issue by AshleySetter** [Kiarash-Z/react-modern-calendar-datepicker#159]
I have a DatePicker component close to the menu bar and when I open it up the left side lies under the menu bar and I've had trouble fixing it, I've tried changing the z-index on the DatePicker component as well as passing in a z-index in a CSS style to calendarClassName and wrapperClassName but it hasn't worked. How can I get the calendar to sit over the menu bar?

https://codesandbox.io/s/app-drawer-menu-with-datepicker-zztb5?file=/src/App.js

**Comment by Kiarash-Z** [comment]
Hi, Thanks for providing a demo. I inspected the material UI drawer and I found that it's using a `1200 z-index`😂:

![image](https://user-images.githubusercontent.com/20098648/84055561-3ff91d80-a9ca-11ea-8625-9934c99b8fd6.png)

Therefore, If you give a higher `z-index` than 1200 to the calendar wrapper using `calendarWrapper` prop, it would work! 🎉 [Here's the demo on CodeSandbox for you!😊](https://codesandbox.io/s/app-drawer-menu-with-datepicker-sspqt?file=/src/App.js:6715-6978)

**Comment by AshleySetter** [comment]
Brilliant, that works great, thanks! For anyone finding this issue in the future and having problems making it work, don't forget that a child component cannot have a higher z-index than it's parent component, see point 4 [here](https://coder-coder.com/z-index-isnt-working/).
