### ISSUE TITLE
Is it correct that you are bunding React in your index.js?

### ISSUE THREAD

**Issue by Hainesy** [Kiarash-Z/react-modern-calendar-datepicker#160]
Your bundled lib/index.js contains React v16.13.0

Is this intended?

**Comment by Kiarash-Z** [comment]
Hi, Bundle doesn't contain React v16.13.0. If it did, it would add up to the size of the library in Bundleophobia. BTW, I just installed the library and checked node_modules, and React wasn't in the final bundle. React has been mentioned as a `peerDependency` in `package.json`, so it wouldn't be present in the bundle.

**Comment by Hainesy** [comment]
So `lib/index.js` appears to contain React and is 43Kb. I don't quite understand your response. Am I misunderstanding something?
This is causing us problems using your library in our own component library as we end up with 2 copies of React.

**Comment by Kiarash-Z** [comment]
You're right. I found that it's actually because of `prop-types` package that I've included

**Comment by Kiarash-Z** [comment]
I fixed this issue. Can you check the latest version (3.1.4) please?
