### ISSUE TITLE
use classs component

### ISSUE THREAD

**Issue by MohsenEs** [Kiarash-Z/react-modern-calendar-datepicker#164]
چطور میتونم توی کامپوننت کلاسی استفاده کنم
و اینکه توی الاید بار که باز میکنم نصفه باز میشه
و بازم اینکه با چه دستوری میتونم input مثل قالب بشه
ممنون
![2020-06-28_16-57-11](https://user-images.githubusercontent.com/46873097/85947522-7fc77b00-b960-11ea-954e-21d5e963f096.jpg)

**Comment by thebrodmann** [comment]
Duplicate of #20 and #38.

**Comment by MohsenEs** [comment]
react modern calender or persian calender ??
how to install persian calender

**Comment by thebrodmann** [comment]
> react modern calender or persian calender ??

Ah, Persian calendar was the formal name of this calendar.

**Comment by Kiarash-Z** [comment]
@MohsenEs Change the `z-index` of the calendar using `containerClassName` prop to fix the calendar getting cropped issue

**Comment by the-dr-lazy** [comment]
I think this issue has been resolved.
