### ISSUE TITLE
change Default Values not work

### ISSUE THREAD

**Issue by elibh159** [Kiarash-Z/react-modern-calendar-datepicker#167]
Hi ,
How can I change Default Value after First load page ?
for example when my component load , my default Value is null and it's true, but after fetch data I need set Date by new value and I set default value by new data but my calendar doesn't change ?!
this is my code: 
 const [defaultValuePerCal, setDefaultValuePerCal] = useState(null)
   <PersianCalender  defaultValue={defaultValuePerCal} />

after fetch data  I set default Value like this but my calender doesn't work:
 var resDate = response.invoice.farsiCreateDate.split("/");
                    var defualtValDate = {
                        year: ~~resDate[0],
                        month: ~~resDate[1],
                        day: ~~resDate[2],
                    }
  setDefaultValuePerCal(defualtValDate)

Thank you

**Comment by Kiarash-Z** [comment]
Hi,

Your issue is actually a React one[. I made a demo for you on CodeSandbox which changes the default value after 5 seconds of component load(similar to doing an asynchronous task)](https://codesandbox.io/s/competent-tereshkova-5n0rf?file=/src/App.js). Here's how the code looks like:

```js
import "react-modern-calendar-datepicker/lib/DatePicker.css";
import { Calendar } from "react-modern-calendar-datepicker";
import React, { useState, useEffect } from "react";
import "./styles.css";

export default function App() {
  const [value, setValue] = useState(null);

  useEffect(() => {
    const newValue = {
      year: 1400,
      month: 1,
      day: 1
    };
    setTimeout(() => {
      setValue(newValue);
    }, 5000);
  }, []);

  return (
    <div className="App">
      <h1>Value Will Change After 5 Seconds</h1>
      <Calendar value={value} onChange={setValue} locale="fa" />
    </div>
  );
}

```

**Comment by elibh159** [comment]
Thank you so much, my problem solved by useEffect.
