### ISSUE TITLE
not correct in class compnent

### ISSUE THREAD

**Issue by MohsenEs** [Kiarash-Z/react-modern-calendar-datepicker#169]
im ask issues #164 
not correct #38
when select date state fill but input date not fill?

But with 'react-persian-calendar-date-picker' no problem only css bug

**Comment by Kiarash-Z** [comment]
This is a little bit awkward. Can you please reproduce this on [CodeSandbox](https://codesandbox.io/)?

**Comment by MohsenEs** [comment]
https://codesandbox.io/s/sad-williams-s49qr?file=/src/App.js

**Comment by Kiarash-Z** [comment]
@MohsenEs There's no `selectedDay` prop anymore! If you replace the `selectedDay` with `value` prop, [it would work fine](https://codesandbox.io/s/wonderful-mahavira-137q4). I would highly recommend [reading the docs.](https://kiarash-z.github.io/react-modern-calendar-datepicker/docs/core-concepts)

**Comment by MohsenEs** [comment]
Tanks
