### ISSUE TITLE
get value

### ISSUE THREAD

**Issue by MohsenEs** [Kiarash-Z/react-modern-calendar-datepicker#170]
hi tanks for date picker
When I want to receive and receive information in the form of an array, I converted it to a string that I can send to the server with the following code
, But when the day and month are below 10, it will not be sent to the server

`ExpirationCardDate:
        newValue.year + "-" + newValue.month  + "-" + newValue.day,`

![2020-07-14_20-04-25](https://user-images.githubusercontent.com/46873097/87460995-fcc24800-c622-11ea-9c83-4beddb4abf1e.jpg)

**Comment by Kiarash-Z** [comment]
Hi, It doesn't have anything to do with the date picker. Your value is correct. The date picker handles the stuff on the client-side and it has nothing to do with the server. You should probably insert a `0` before month and day value.
