### ISSUE TITLE
API change (V2 roadmap)

### ISSUE THREAD

**Issue by thebrodmann** [Kiarash-Z/react-modern-calendar-datepicker#22]
Currently, as component's functionality grows, API grows too (as in #21). So maybe it would be an API reconsideration symptom.
Maybe we can determine all 3 types of date pickers based on the input value and there is no need for the extra properties. So in this way, we can make API simpler.

### Single Date Selection

```js
const [date, setDate] = useState(undefined)

<Datepicker value={date}
            onChange={setDate}  />
```

### Range Date Selection

```js
const [dateRange, setDateRange] = useState({ from: undefined, to: undefined })

<Datepicker value={dateRange}
            onChange={setDateRange} />
```

### Multiple Dates Selection

```js
const [dates, setDates] = useState([])

<Datepicker value={dates}
            onChange={setDates}  />
```

As the above API suggests we can differentiate between 3 types of date pickers by the type of `value` property that has been sent to the component.

- `undefined`/`null`: single-day selection
- `{ from: undefined, to: undefined }`: range-day selection
- `Array`: multiple-dates selection

Changes that should be considered in moving from the current API to the suggested API is as follow:

- replace `selectedDay` and `selectedDayRange` with `value` property (Also there is no need for `selectedDays` property for multiple-days selection).
- remove `isDayRange` property (Also there is no need for `isMultiSelectable` property for multiple-days selection).

As the suggested API is similar to related HTML tags (e.g. `<input type="date">` and `<select>`) maybe it would be better to use conventional interface for `minimumDate` and `maximumDate` which are [`min`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/date#min) and [`max`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/date#max) respectively in HTML `<input type="date">` tag.
BTW, this is a huge breaking change for the API but I think the simpler API will worth it.

**Comment by Kiarash-Z** [comment]
@thebrodmann I like this approach but for now, bumping the version to 2.x is not intellectual. Therefore, I'd like to wait for some other feature requests besides multiselection.

**Comment by Kiarash-Z** [comment]
We will support gregorian date in v2 as well!🎉

**Comment by Kiarash-Z** [comment]
🎉 A new feature requested and I will add a custom way for rendering a single day item for customization purposes.

**Comment by Kiarash-Z** [comment]
🎉 the package has been renamed and republished!

**Comment by Aryan-mor** [comment]
> 🎉 A new feature has been requested, and I will add a custom way for rendering a single day item for customization purposes.

Hello, this feature is not ready yet?

**Comment by Kiarash-Z** [comment]
@Aryan-mor Hey, Unfortunately, not yet. I will consider adding it soon(working on an efficient way for this)
