### ISSUE TITLE
Open the date picker programmatically.

### ISSUE THREAD

**Issue by LevKozak** [Kiarash-Z/react-modern-calendar-datepicker#238]
Hello,

Is there any way how to open the date picker from JS? For instance, if I have an icon next to the input (or on top of it), how can I fire an action to open the date picker?
Because I don't see any exposed callbacks for such a thing.

Thank you in advance.

**Comment by pulpdood** [comment]
You can use the ref passed into the customInput and use `ref.current.focus()`
