### ISSUE TITLE
How to use with keyboard?

### ISSUE THREAD

**Issue by J-Kallunki** [Kiarash-Z/react-modern-calendar-datepicker#54]
**Describe the bug**
For keyboard / accessibility component shows as input but nothing else. How to select day with keyboard?

**Reproduced Version on CodeSandbox**
Here it is on CodeSandBox: https://codesandbox.io/s/sad-chatelet-t4s0p

**Expected behavior**
Input needs to have guidance for screenreader and keyboard can be used to go through calendar and select days.

**Comment by Kiarash-Z** [comment]
Hi Joonas,

Thanks for the suggestion. Accessibility will definitely improve in the next release. I keep this issue open till the fix 👍

**Comment by jeffcrump** [comment]
I'd recommend changing the label back to a bug for this issue, and a critical one at that. Keyboard access is one of the lowest-level accessibility guidelines ([WCAG 2.1.1 Keyboard](https://www.w3.org/TR/UNDERSTANDING-WCAG20/keyboard-operation-keyboard-operable.html)) and is a breaking experience for any user that uses keyboard as a primary navigation tool. 

This project is positioned as a drop-in datepicker component, and that makes it even more of a critical bug to fix; anyone who uses this for their own project in the current state will run afoul of the guideline.

**Comment by Kiarash-Z** [comment]
Thanks, @jeffcrump for the clarification 🙏🏻. I'm working on the new release 😇

**Comment by Kiarash-Z** [comment]
@J-Kallunki @jeffcrump This is now fixed in v1.1.0 🎉 date picker is now accessible with keyboard and there are huge accessibility improvements.

**Comment by jeffcrump** [comment]
Awesome work, @Kiarash-Z !
