### ISSUE TITLE
Hardcoded texts not translatable

### ISSUE THREAD

**Issue by J-Kallunki** [Kiarash-Z/react-modern-calendar-datepicker#55]
**Describe the bug**

Cannot translate hardcoded texts like:
https://github.com/Kiarash-Z/react-modern-calendar-datepicker/blob/master/src/components/Header.js#L101

**Expected behavior**

Hardcoded texts to be implemented so that changeable via the API

**Comment by Kiarash-Z** [comment]
Hi Joonas,

Why does it not translatable? it is explicitly set it's 'previous month', and on the Persian calendar, it's the equivalent phrase.

**Comment by J-Kallunki** [comment]
How do you use it with another language than english or persian? If html document lang-attribute is saying content is different language it would be accessibility issue to use wrong language at datepicker.

**Comment by J-Kallunki** [comment]
Sorry I mean localization. If html document uses other languahe than english or persian - how do you change all texts to webpages language?

**Comment by Kiarash-Z** [comment]
I think this localization should be applied when other language locales get added. For now, I guess English is fine.

**Comment by Kiarash-Z** [comment]
@J-Kallunki This is now fixed in v1.1.0 🎉 there's a new file for language and localization specs.

**Comment by J-Kallunki** [comment]
It is a good start but would it be easier to give other localization translations as configuration for the component? Default to those hardcoded languages if they serve the need else.

**Comment by Kiarash-Z** [comment]
@J-Kallunki Thanks for your suggestion, I will consider this in the next version(though there will be more locales added)
