### ISSUE TITLE
Cleartype/subpixel is disabled

### ISSUE THREAD

**Issue by HosseinAlipour** [Kiarash-Z/react-modern-calendar-datepicker#59]
I'm not sure this is the issue with the project or a bug in browsers. the input text is rendered without cleartype/subpixel when magnified, 

with cleartype
![Screenshot (63)](https://user-images.githubusercontent.com/5198502/67974923-7f87ac00-fc28-11e9-9966-7531517da829.png)

without cleartype
![Screenshot (62)](https://user-images.githubusercontent.com/5198502/67974964-929a7c00-fc28-11e9-9639-88db4230d1ab.png)

normally it's hard to notice with the naked eye, but I can notice it, and it makes an inconsistent look.

**Comment by Kiarash-Z** [comment]
Hi Hossein,

This is definitely not this library's bug 😊 (By the way this picker doesn't use any font on its own. it just inherits it)

**Comment by HosseinAlipour** [comment]
Are you saying that you don't have this issue? I've could resolve the issue by separating Input from the Picker into another tree as well as disabling `z-index` on Datepicker. but it needs forking and working on the project separately(something I really try to avoid), I wonder where this problem originated from. it happens in Opera and Chrome but not Firefox. do you have any idea?
