### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by arminyahya** [Kiarash-Z/react-modern-calendar-datepicker#60]
Calendar needs index.d.ts file or @types so project with typescript base can have their type checking

**Comment by Kiarash-Z** [comment]
Hi @arminyahya,

Does this index.t.ts file need to be published on NPM? or it just gets fetched automatically by the repo connected to the package?

**Comment by thebrodmann** [comment]
@Kiarash-Z it should publish. I can work on this.

**Comment by arminyahya** [comment]
I added new branch for this feature and after merge, your package need a new version(like 1.1.0) and need to publish on npm

**Comment by Kiarash-Z** [comment]
@thebrodmann @arminyahya  Wouldn't this result in extra bundle size?

**Comment by arminyahya** [comment]
@Kiarash-Z 
No, this is only for developer experience and doesn't effect the main bundle

**Comment by Kiarash-Z** [comment]
@arminyahya just tried it, and it adds up to bundle size 😶

**Comment by Kiarash-Z** [comment]
Gotta do some research to find an efficient way to add this 🤔

**Comment by arminyahya** [comment]
@Kiarash-Z  @thebrodmann
There is another way and its i add this index.d.ts file as a package to DefinitelyTyped so developers can install types (like @types/react-modern-calendar-datepicker).
Im glad to do that too.

**Comment by thebrodmann** [comment]
@Kiarash-Z can you share statistics? It should not affect the JS part of the package!

> There is another way and its i add this index.d.ts file as a package to DefinitelyTyped so developers can install types (like @types/react-modern-calendar-datepicker).

I don't recommend this solution. Usually, It's a plan B when maintainers of a module don't wanna accept the maintenance of the type definition.

**Comment by Kiarash-Z** [comment]
@thebrodmann I just considered it simple. When it's gonna get published, it will be there on node_modules/react-modern-calendar-datepicker, and that means it would add up to bundle size, wouldn't it? If it's not going to be there then how developers would detect the types?

**Comment by thebrodmann** [comment]
@Kiarash-Z module bundlers won't load type definition files and consequently type definitions will not appear in the JS bundle files. In fact, the **package size will grow** but the bundle size will not.
Type definitions only will be load by TypeScript compiler from `types` property in `package.json` file.

**Comment by Kiarash-Z** [comment]
@thebrodmann Got it! thanks for the clear explanation. You can work on a PR for this if you wish. By the way, adding types by an index.d file.ts is the best way?

**Comment by arminyahya** [comment]
@Kiarash-Z  @thebrodmann 
I did a PR for this before.
Didn't you Receive that?

**Comment by Kiarash-Z** [comment]
@arminyahya Nope. Nothing in Pull Requests section:/

**Comment by arminyahya** [comment]
Hmm
I finished this last week i maybe forget something.
Let me back home and create a PR.

**Comment by thebrodmann** [comment]
> By the way, is adding types by an index.d.ts file the best way for adding types?

Yeah, I think so. It's our plan A. :D

**Comment by Kiarash-Z** [comment]
Resolved in #64
