### ISSUE TITLE
how can I use refs for datepicker?

### ISSUE THREAD

**Issue by mahyalpr** [Kiarash-Z/react-modern-calendar-datepicker#62]
I set the datepicker into a dropdown . when click the datepicker dropdown closed , I tried to use refs to solve this problem but always return null ,
what do I do ??????????????

**Comment by Kiarash-Z** [comment]
Hi @mahyalpr, 

You can wrap the date picker in a `div` element and give that a ref. That would resolve your issue

**Comment by mahyalpr** [comment]
I NEED to use ref for datepicker ,does datepicker accept ref?
