### ISSUE TITLE
accessibility support

### ISSUE THREAD

**Issue by kisin** [Kiarash-Z/react-modern-calendar-datepicker#65]
Do you plan on adding accessibility support to the calendar?

its the only thing stoping me from using your great calendar component
as accessibility is mandatory on my country.

we need full keyboard support and aria rules all over the place.

thanks.

**Comment by Kiarash-Z** [comment]
Hello @kisin. I'm sorry for the latency in responding; I had a connection issue. Yes, I'm working on the new version which focuses on accessibility improvements 😊❤️

**Comment by Kiarash-Z** [comment]
@kisin date picker is now accessible in version 1.1.0 🎉check it out!
