### ISSUE TITLE
render custom element in Datepicker

### ISSUE THREAD

**Issue by spostad7** [Kiarash-Z/react-modern-calendar-datepicker#68]
thanx in advance for this great package,
I am creating a full-page datepicker and I need to add some custom elements in opening datepicker, for example, I need to implement today button and also I want to add a close button and header title in datepicker
how can I achieve this?
something like this is in my mind:

![69562969-7db1ce00-0fc5-11ea-8ff6-6aa32e77a9d6](https://user-images.githubusercontent.com/2351721/69564357-2103e280-0fc8-11ea-9d91-9a31759bb086.png)

**Comment by Kiarash-Z** [comment]
Hey @spostad7, rendering custom elements is not possible yet. in your image, the close button seems separated from the date picker. You can put `<Calendar/>` in a modal and put a close button for the modal. For the today button, you can create a button yourself and when it gets clicked you can change the value of datepicker
