### ISSUE TITLE
Modal DatePicker

### ISSUE THREAD

**Issue by kindslayer** [Kiarash-Z/react-modern-calendar-datepicker#69]
Is it impossible add feature show panel in a modal like this.
![image](https://user-images.githubusercontent.com/19972901/69713597-0e012780-111a-11ea-9c85-d8d58f009bad.png)

**Comment by Kiarash-Z** [comment]
Hi @kindslayer, Yes, for such purposes, use `<Calendar/>` instead of `<Datepicker/>`. You can put calendar in any modal wrapper like [Rodal](https://chenjiahan.github.io/rodal/)
