### ISSUE TITLE
Use bootstrap

### ISSUE THREAD

**Issue by alidehghan** [Kiarash-Z/react-modern-calendar-datepicker#70]
Thanks for your sleek date-picker. 

Would you create a branch and use bootstrap as theme?

**Comment by Kiarash-Z** [comment]
Hi @alidehghan, I think bootstrap's theme is not really that good. I would consider adding various beautiful themes for date picker though.

**Comment by alidehghan** [comment]
Yes, you are right. but bootstrap is main css-framework which widely used in many projects and is keystone of many infrastructures. By adapting bootstrap, your nice component would be more customizable and easier to utilize in projects.

**Comment by Kiarash-Z** [comment]
@alidehghan I understand your case, but for now, this can't be implemented. There are a couple of things you can do to customize date picker:
1- Change `primaryColor` and `secondaryColor` props e.g to bootstrapy purple
2- As you might have noticed, when using this component you import component defined CSS file like `import 'react-modern-calendar-datepicker/lib/DatePicker.css';` you can inspect elements and override any style you would like to make them look like more bootstrap theme.(though here are a couple of pre-defined props like `calendarContainerClassName`)
