### ISSUE TITLE
Unhandled Rejection (TypeError): Cannot read property 'offsetTop' of null

### ISSUE THREAD

**Issue by benamm** [Kiarash-Z/react-modern-calendar-datepicker#71]
**Describe the bug**

TypeError: Cannot read property 'offsetTop' of null
(anonymous function)
node_modules/react-modern-calendar-datepicker/lib/components/YearSelector.js:42
  39 |   var classToggleMethod = isOpen ? 'add' : 'remove';
  40 |   var activeSelectorYear = wrapperElement.current.querySelector('.Calendar__yearSelectorItem.-active');
  41 |   wrapperElement.current.classList[classToggleMethod]('-faded');
> 42 |   yearListElement.current.scrollTop = activeSelectorYear.offsetTop - activeSelectorYear.offsetHeight

**Comment by Kiarash-Z** [comment]
Hello @benamm, can you provide an example on [CodeSandbox](https://codesandbox.io/)?

**Comment by arminyahya** [comment]
I had this problem.
For mine this happens when I gave calendar Persian value  but not giving Calendar component isPersian={true}
After that problem solved.
Be sure your value and isPersian prop are compatible.
@benamm

**Comment by Kiarash-Z** [comment]
@arminyahya I could reproduce this issue like this and it's because a Persian value given to Gregorian date picker, is out of its minimum date limits(compare 2019 to 1398!). However, I will throw an error for such a case in the next versions.
