### ISSUE TITLE
isPersian directive is not working anymore

### ISSUE THREAD

**Issue by SidMorad** [Kiarash-Z/react-modern-calendar-datepicker#79]
So everything is working as expected when I do test my `DatePicker` component in a desktop browser. But `isPersian` directive has no effect when my testing device is a phone. e.g. Google chrome in Android or Safari in iOS. 

Is this a bug? or am I missing something? please let me know how can I help? Thanks.

**Comment by Kiarash-Z** [comment]
Hi @SidMorad, API has changed in v1.1.0 and `isPersian` prop has been removed. You can use `locale="fa"` instead. [here are some examples in the docs](https://kiarash-z.github.io/react-modern-calendar-datepicker/docs/different-locales).

**Comment by SidMorad** [comment]
@Kiarash-Z Thank you for a fast response. Yes that was the root of issue.

I replace all `isPersian` with `locale='fa'` and I set version from `^1.0.1` to `1.1.0`.

**Comment by SidMorad** [comment]
#90 related.

**Comment by spostad7** [comment]
the locale='fa' just add the class '-fa' to DOM, but in style, there is '-rtl' class that defines the style for left2right lang.
with these changes in the new release, I had to change almost most part of my styles due to match with new datepicker  :-)

**Comment by Kiarash-Z** [comment]
@spostad7 Sorry about that, but that's what a BREAKING change means.

**Comment by spostad7** [comment]
@Kiarash-Z 
have u check locale='fa'?
I think there is a mistake in the CSS class, because it uses .rtl class instead of '.fa' or '-fa' class

**Comment by Kiarash-Z** [comment]
@spostad7 It's actually right because the style changes applied for `locale="fa"` are only because of reversing the direction of some elements, and that's because Persian is RTL. If in any future release I add another locale for Arabic or any other RTL language, this `-rtl` class modifier will be still valid which is not the case with `-fa` modifier.
