### ISSUE TITLE
use hour in this datepicker

### ISSUE THREAD

**Issue by mahyalpr** [Kiarash-Z/react-modern-calendar-datepicker#85]
does this datePicker or Calender supports the hour ?
I use this calender for date filtering and now i need to filter hour with date

**Comment by Kiarash-Z** [comment]
Hi @mahyalpr, at the current stage, no, however, I'm planning to release a **separate time picker module**. Would that resolve your issue?

**Comment by Kiarash-Z** [comment]
Closed due to inactivity
