### ISSUE TITLE
How can I hide arrow that is added a the bottom?

### ISSUE THREAD

**Issue by vbtux** [Kiarash-Z/react-modern-calendar-datepicker#86]
When I add this datePicker to my class component ,It will show an arrow at the bottom, how can I hide it?

**Comment by Kiarash-Z** [comment]
This is so vague.  Can you provide a screenshot? a demo on [CodeSandbox](https://codesandbox.io/) is preferred.

**Comment by vbtux** [comment]
![Untitled](https://user-images.githubusercontent.com/5327182/70696122-4be47b00-1cd8-11ea-89df-bf11eea2a10a.png)

**Comment by Kiarash-Z** [comment]
@vbtux This is an unexpected behavior. Can your reproduce this on [CodeSandbox](codesandbox.io)?

**Comment by thebrodmann** [comment]
I remember having seen this behaviour on [Customization](https://kiarash-z.github.io/react-modern-calendar-datepicker/docs/customization) page too.

**Comment by thebrodmann** [comment]
@Kiarash-Z if you change the background color of the container that contains the datepicker input you will be able to see the arrow.

![Screen Shot 2019-12-12 at 1 04 47 PM](https://user-images.githubusercontent.com/20781126/70700463-06c44700-1ce0-11ea-8f1b-8f7badb5370d.png)

**Comment by Kiarash-Z** [comment]
@thebrodmann Thanks for letting me know this. I'm gonna release a fix now

**Comment by vbtux** [comment]
https://codesandbox.io/s/hungry-surf-4vubf?fontsize=14&hidenavigation=1&theme=dark

**Comment by Kiarash-Z** [comment]
@vbtux Check the latest version (1.1.3) and it's fixed😊

**Comment by Kiarash-Z** [comment]
@vbtux this fix actually caused a new bug(#88) I fixed that as well. Please use 1.1.4 😁
