### ISSUE TITLE
Arrow position not correct when date picker is out of window bounds

### ISSUE THREAD

**Issue by Kiarash-Z** [Kiarash-Z/react-modern-calendar-datepicker#88]
![image](https://user-images.githubusercontent.com/20098648/70702274-0e391f80-1ce3-11ea-879f-d3996bd698db.png)

**Comment by thebrodmann** [comment]
Maybe we should add a state class (e.g. `-is-active`) to `.DatePicker` and move the `::after` pseudo-element back to the `.DatePicker` class.

**Comment by Kiarash-Z** [comment]
Fixed in 1.1.4
