### ISSUE TITLE
Api change in a minor release

### ISSUE THREAD

**Issue by saeed-mosavat** [Kiarash-Z/react-modern-calendar-datepicker#90]
**Describe the bug**
My code was broken after running a `yarn install` on a different machine.
The input of locale utilities has been changed (from `true/false` to `'fa'/'en'`) since `v1.1.0` and this utitlity was exported in the index file. So I think this is an API Change and requires a **major** version upgrade not a minor one.

**Expected behavior**
No change in api should be experienced on minor upgrades.

**Comment by thebrodmann** [comment]
**BREAKING CHANGE** caused by 240b4f36f0d60114b3951b1c626c3e48cef0607b

**Comment by Kiarash-Z** [comment]
Hi @saeed-mosavat,I'm sorry about this ❤️. In fact, I just considered the calendar API for such changes. It never occurred to my mind that utils will have a BREAKING CHANGE. Now we're at 1.1.4. id doesn't make sense to bump version only for this. I would consider these changes more carefully in the next releases 👾

**Comment by Kiarash-Z** [comment]
@saeed-mosavat @thebrodmann just released 2.0.0 with no changes because of this👍
