### ISSUE TITLE
TypeError ReactJS

### ISSUE THREAD

**Issue by namipsg** [Kiarash-Z/react-modern-calendar-datepicker#91]
TypeError: o is not a function
y
node_modules/react-modern-calendar-datepicker/lib/index.js:1

it gets this error when render function executes 
`<DatePicker
                                    selectedDay={today}
                                    inputPlaceholder="date" // placeholder
                                    formatInputText='YYYY/MM/DD' // format value
                                    inputClassName="input" // custom class
                                    shouldHighlightWeekends
                                />`

{today} is defined in the code
css is imported.

**Comment by thebrodmann** [comment]
Hey @namipsg, can you provide a repro through a [CodeSandBox](https://codesandbox.io/)?

**Comment by Kiarash-Z** [comment]
Hi @namipsg, as it's mentioned in [Props List page](https://kiarash-z.github.io/react-modern-calendar-datepicker/docs/props-list), **you should use a function for `formatInputText`**. `string` is not a valid value for this prop. There are a couple of examples for this on [Customization page](https://kiarash-z.github.io/react-modern-calendar-datepicker/docs/customization)

**Comment by namipsg** [comment]
Thanks a lot @Kiarash-Z ! one more question do you have any suggestions that how we can enable auto tab on this module? i mean if we have 2 DatePicker's and user selects first date , first input automatically closes and second DatePicker opens instantly

**Comment by Kiarash-Z** [comment]
@namipsg You can do that [like this demo on CodeSandbox](https://codesandbox.io/s/pensive-stallman-m1d9g?fontsize=14&hidenavigation=1&theme=dark), but instead of 2 separate datepickers, I would recommend using a single range date picker.
