### ISSUE TITLE
range persian datepicker

### ISSUE THREAD

**Issue by MasoumeAfshar** [Kiarash-Z/react-modern-calendar-datepicker#92]
when I want to use this calendar for **Persian range,** it makes an error and exactly not work, :(
please add this feature soon, thx

**Comment by Kiarash-Z** [comment]
Hi @mafshark, this is so vague. What error does it throw? I just tried Persian range picker and it's working perfectly: [CodeSandbox working demo](https://codesandbox.io/s/dank-resonance-9e250?fontsize=14&hidenavigation=1&theme=dark)

**Comment by MasoumeAfshar** [comment]
this is my code
![Screenshot from 2019-12-17 15-43-15](https://user-images.githubusercontent.com/30409314/70994700-06fb8280-20e4-11ea-8ee7-2403cd841433.png)



`import React, { useState } from "react";
import "react-modern-calendar-datepicker/lib/DatePicker.css";
import DatePicker from "react-modern-calendar-datepicker";
import './style.scss'

const DP = () => {

  const [selectedDay, setValue] = useState({ from: null, to: null });
  
  return (
    <DatePicker
      locale="fa"
      value={selectedDay}
      onChange={setValue}
      shouldHighlightWeekends
    />
  );
};
export default (DP);`

**Comment by MasoumeAfshar** [comment]
this is my code 
![Screenshot from 2019-12-17 15-43-15](https://user-images.githubusercontent.com/30409314/70994793-3611f400-20e4-11ea-8911-af0f5739a9ac.png)

`import React, { useState } from "react";
import "react-modern-calendar-datepicker/lib/DatePicker.css";
import DatePicker from "react-modern-calendar-datepicker";

const DP = () => {
  const [selectedDay, setValue] = useState({ from: null, to: null });
  return (
    <DatePicker
      locale="fa"
      value={selectedDay}
      onChange={setValue}
      shouldHighlightWeekends
    />
  );
};
export default (DP);`

**Comment by thebrodmann** [comment]
@MasoumeAfshar Did you set `locale` prop to `'fa'` in the `Datepicker` component?

```js
<DatePicker
   locale="fa"
   value={selectedDay}
   onChange={setValue}
/>
```

**Comment by Kiarash-Z** [comment]
@MasoumeAfshar `return` is empty in this code 😑

**Comment by MasoumeAfshar** [comment]
import React, { useState } from "react";
import "react-modern-calendar-datepicker/lib/DatePicker.css";
import DatePicker from "react-modern-calendar-datepicker";
import './style.scss'

const DP = () => {

  const [selectedDay, setValue] = useState({ from: null, to: null });
  
  return (
    <DatePicker
      locale="fa"
      value={selectedDay}
      onChange={setValue}
      shouldHighlightWeekends
    />
  );
};


export default (DP);

**Comment by MasoumeAfshar** [comment]
return (
    <DatePicker
      locale="fa"
      value={selectedDay}
      onChange={setValue}
      shouldHighlightWeekends
    />
  );

**Comment by MasoumeAfshar** [comment]
<DatePicker
      locale="fa"
      value={selectedDay}
      onChange={setValue}
      shouldHighlightWeekends
    />

**Comment by MasoumeAfshar** [comment]
<DatePicker
      locale="fa"
      value={selectedDay}
      onChange={setValue}
      shouldHighlightWeekends
    />

**Comment by MasoumeAfshar** [comment]
<DatePicker
      locale="fa"
      value={selectedDay}
      onChange={setValue}
      shouldHighlightWeekends />

**Comment by MasoumeAfshar** [comment]
![Screenshot from 2019-12-17 15-43-15](https://user-images.githubusercontent.com/30409314/70995499-eb917700-20e5-11ea-9487-8327f03154ce.png)

```
import React, { useState } from "react";
import "react-modern-calendar-datepicker/lib/DatePicker.css";
import DatePicker from "react-modern-calendar-datepicker";

const DP = () => {
  const [selectedDay, setValue] = useState({ from: null, to: null });
  return (
    <DatePicker
      locale="fa"
      value={selectedDay}
      onChange={setValue}
      shouldHighlightWeekends
    />
  );
};
export default (DP);
```

**Comment by thebrodmann** [comment]
What is the version of the library you are using?
You can find it by running following command in the root of your project:
```sh
npm ls react-modern-calendar-datepicker
```

**Comment by MasoumeAfshar** [comment]
`react-modern-calendar-datepicker@1.0.1 `

**Comment by thebrodmann** [comment]
Please run the following command in the root of your project:
```sh
npm update react-modern-calendar-datepicker@^1.1.4
```

**Comment by thebrodmann** [comment]
@Kiarash-Z we should do something for the breaking change mentioned in #90. We can fix it or just let the developers know that there was a breaking change in README or documentation website.

**Comment by Kiarash-Z** [comment]
@thebrodmann just released 2.0.0 with no changes because of this👍

**Comment by Kiarash-Z** [comment]
@MasoumeAfshar please install the latest version and your issue should be fixed😇

**Comment by MasoumeAfshar** [comment]
I updated the version and it was fixed , thx :+1:
