### ISSUE TITLE
showing two months, current month and next month

### ISSUE THREAD

**Issue by MasoumeAfshar** [Kiarash-Z/react-modern-calendar-datepicker#94]
hi, I want to show two months exactly together I mean current month and next month , how can  I do that 
![Screenshot from 2019-12-22 14-54-10](https://user-images.githubusercontent.com/30409314/71321153-fa53a180-24ca-11ea-84b5-929c2b2f41a8.png)

**Comment by Kiarash-Z** [comment]
Hi, For now, This is not possible yet because it would add extra complexity to the project
