### ISSUE TITLE
minimum date for "to" date should be more than "from" date  in Range Date picker 

### ISSUE THREAD

**Issue by MasoumeAfshar** [Kiarash-Z/react-modern-calendar-datepicker#95]
I use Range Datepicker, it isn't correct that "from" date be equal with the "to" date, minimum date for the "to" date should be more than "from" date

```
from: {day: 9, month: 10, year: 1398}
to: {day: 9, month: 10, year: 1398}
```

**Comment by Kiarash-Z** [comment]
@MasoumeAfshar This is the expected behavior. Imagine you want to select a day range for your payments, and you want to see only today's payments. How would you select that(with keeping the functionality for other ranges selection)?

**Comment by MasoumeAfshar** [comment]
This usage is less likely to occur, Why use Range in these circumstances, to see only today's payments!!
This is not good for booking and at least has the ability to set limits for the "to" date

**Comment by Kiarash-Z** [comment]
@MasoumeAfshar This is actually quite popular! I used it many times in my projects. However, this date picker is quite customizable. You can easily control this behavior by checking `value` in `onChange` callback. Just make sure to is not equal to from, if it is, don't update the state and show an error for the user.

**Comment by MasoumeAfshar** [comment]
thx
