### ISSUE TITLE
Calendar crash

### ISSUE THREAD

**Issue by iksent** [Kiarash-Z/react-modern-calendar-datepicker#96]
Crash while openning Calendar.

![2019-12-30_11-40-37](https://user-images.githubusercontent.com/32956521/71570878-3608ef80-2af9-11ea-986c-1a433e81f8cc.png)

Code:
```
<Calendar
  value={{day: 1, month: 1, year: 1200}} <---- YEAR is a problem
  onChange={this.onAccept}
  shouldHighlightWeekends
  colorPrimary="#168093"
  colorPrimaryLight="#168093"
  slideAnimationDuration="0.1s"
  calendarClassName="date-picker-v3"
/>
```

**Comment by Kiarash-Z** [comment]
Hi, This is because of giving invalid year(1200) which is out of valid calendar bounds. You can specify minimum selectable year and fix this error by setting `selectorStartingYear` prop to `1100` for example.

**Comment by iksent** [comment]
Ok, thanks, but anyway crush is a problem :)

**Comment by Kiarash-Z** [comment]
That is right. I will implement a cash-free behavior for this👍

**Comment by Kiarash-Z** [comment]
moved to #105
