### ISSUE TITLE
Weird behavior by clicking on Month/Year pickers

### ISSUE THREAD

**Issue by iksent** [Kiarash-Z/react-modern-calendar-datepicker#97]
**Describe the bug**
If you click on the month select, after that click on the empty space near the select:

<img src="https://user-images.githubusercontent.com/32956521/71571089-787efc00-2afa-11ea-9e0e-122ac5ab9f43.png" width="300">

we will see that the month-picker has disappeared:

<img src="https://user-images.githubusercontent.com/32956521/71571091-7ae15600-2afa-11ea-8bc0-22bd7fa4f68f.png" width="300">

Same thing for year picker:

<img src="https://user-images.githubusercontent.com/32956521/71571123-a49a7d00-2afa-11ea-8d7d-5bc89ef68e4f.png" width="300">
<img src="https://user-images.githubusercontent.com/32956521/71571127-a7956d80-2afa-11ea-9398-2c48feaccb8d.png" width="300">

**Comment by Kiarash-Z** [comment]
@iksent Thanks for letting me know. I will fix this in the next release ASAP

**Comment by Kiarash-Z** [comment]
moved to #105
