### ISSUE TITLE
Feature / Prop for locales strings + Week shift

### ISSUE THREAD

**Issue by iksent** [Kiarash-Z/react-modern-calendar-datepicker#99]
**Locale feature description**
Please, provide a prop for setting up an object like `localeLanguages.en` from this: https://github.com/Kiarash-Z/react-modern-calendar-datepicker/blob/master/src/shared/localeLanguages.js
This is a must-have feature, because it is impossible to use this calendar without localization in the desired language. And in order not to wait until all languages ​​are added, prop is needed. In addition, anyone will be able to customize the strings as he needs, even if his locale was already added.

**Week shift feature description**
Also need the ability to shift the week.
For example, calendars in Russia are started from Monday to Sunday. Now, by default, the picker starts the week from Sunday to Saturday.

**Comment by Kiarash-Z** [comment]
@iksent Fantastic ideas, thank you! 😍 I will work on them for the next version

**Comment by Kiarash-Z** [comment]
Moved to #105
